### PR TITLE
Implements overlay scorllbar for terminal.

### PR DESCRIPTION
**Pull request by yharsh**
- Provide line by line scrolling
- Provide multiline scrolling using draggable scrollbar handler

Signed-off-by: Harsh Yadav <harshyadav2829@gmail.com>

### CODE REVIEW

**Comment by yharsh** [comment]
I have developed scrollbar for the terminal. It provides line by line as well multi-line scrolling. When the lines exceed the displayable line limit it will be shown. To scroll you have to hove near the scrollbar where a floating control will appear. One can use mouse pointer to scroll the screen either by clicking up/down arrow icon on the floating control or just dragging that control in order to scroll multiple lines.

**Comment by skavanagh** [comment]
Thanks @yharsh ! I'll try and work this in somehow. I may modify to use the bootstrap fonts.

**Comment by yharsh** [comment]
I have removed the dependency on font-awesome. Instead of that I am using Unicode character for up and down arrow.

**Comment by yharsh** [comment]
Thanks @skavanagh  for showing the interest. Any plan for the adoption of this pull request?

**Comment by skavanagh** [comment]
The handle seems off to me.. It follows the mouse around, instead of where you are at in the scroll log. Looks like it's on-move too, rather than following the drag. I was going go through to see if I can't make improvements (but haven't had any time yet).  Thanks @yharsh 

scroll

**Comment by yharsh** [comment]
**Scrollbar Handler**
- Visible when mouse pointer enters space near to the right edge of the terminal
- Follows mouse pointer
- Has two buttons Up(up arrow) and Down(down arrow)
- To scroll either click Up/Down button or click anywhere on handler and drag for bulk scrolling

So basically its position is independent of scroll-able(whole) content and it is relative to mouse pointer.

**Scrollbar**
- Shows current scroll log
- It's position shows amount of scroll-able text(up/down)
- It's position is automatically adjusted according to the relative position of text shown in the terminal of the whole content(visible/invisible in terminal).
- It is non draggable and non clickable. So to scroll, use Scrollbar Handler instead

**Comment by preetampatil3d** [comment]
Hello @yharsh , i am using this scroll in my application but getting one issue. wherever i past some content to terminal multiple time. it overriding same line after line has full.

Please let me know solution .
Thanks in advance.

**Comment by yharsh** [comment]
@preetampatil3d  I think the issue is there in term.js not in scrollbar.js. It should be reported at https://github.com/chjj/term.js/.

**Comment by preetampatil3d** [comment]
k thanks @yharsh. i will also check with term.js .  

But i have one doubt! if i remove scrollbar.js it works fine.

**Comment by preetampatil3d** [comment]
@yharsh , So updating new term.js might have solved your problem? right! Or have you solved this problem with different solution?
if you know any alternate way for scrollbar then please let me know.

Thanks

**Comment by preetampatil3d** [comment]
@yharsh , i have solved this problem by modifying secure_shell.jsp page.  if you allow i can modify this branch.

**Comment by skavanagh** [comment]
https://github.com/bastillion-io/Bastillion/commit/9ec304f4e93c2fc5f2e61c542e4fee8d7d4dac28

**Comment by foodphoenix** [comment]
Ok
--
从Mail.Ru的Android专用app所发送 星期一, 15 四月 2019, 01:10上午 +08:00 发件人 Sean Kavanagh  notifications@github.com :

**Pull request closed without merging**
